### ISSUE TITLE
Missing comma or intentional

### ISSUE THREAD

**Issue by sunitJindal** [CycoPH/winston-filerotatedate#4]
In file `fileRotateDate.js` where `Stream` is required, it seems a comma is missing. Is it intensional or missed it there?

var events = require('events'),
    fs = require('fs'),
    path = require('path'),
    util = require('util'),
    winston = require('winston'),
    common = require('winston/lib/winston/common')
    Stream = require('stream').Stream;

**Comment by CycoPH** [comment]
Fixed it in version 0,2.0
